version: '3'
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nexus-data:/nexus-data
     ports:
      - 8081:8081
    networks:
      - "dev"
networks:
  dev:
    driver: bridge