version: '3'
services:
  nginx:
    image: sonarqube:alpine
    restart: always
    environment:
      SONARQUBE_JDBC_URL=jdbc:mysql://mysql/sonar
      SONARQUBE_JDBC_USERNAME=root
      SONARQUBE_JDBC_PASSWORD==[;.-pl,0okm
    volumes:
      - './nginx/conf.d/:/etc/nginx/conf.d/:ro'
    networks:
      - dev
    ports:
      - 9000:9000
      - 9092:9092
networks:
  dev:
    driver: bridge