version: '3'
services:
  nginx:
    image: sonarqube:alpine
    restart: always
    volumes:
      - './sonarqube:/opt/sonarqube'
    networks:
      - dev
    ports:
      - 9000:9000
      - 9092:9092
networks:
  dev:
    driver: bridge