version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD==[;.-pl,0okm
      - TZ=Asia/Shanghai
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+8:00' --log-timestamps=SYSTEM
    networks:
      - "dev"
  sonarqube:
    image: sonarqube:alpine
    restart: always
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?createDatabaseIfNotExist=true
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD==[;.-pl,0okm
    networks:
      - dev
    ports:
      - 9000:9000
      - 9092:9092
networks:
  dev:
    driver: bridge