version: '3'
services:
  sonarqube:
    image: sonarqube:alpine
    restart: always
    environment:
      - sonar.jdbc.url=jdbc:postgresql://localhost/sonar
      - sonar.jdbc.username=root
      - sonar.jdbc.password==[;.-pl,0okm
    volumes:
      - ./conf:/opt/sonarqube/conf
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs
      - ./data:/opt/sonarqube/data
    networks:
      - dev
    ports:
      - 9000:9000
      - 9092:9092
networks:
  dev:
    driver: bridge
