version: '3'
services:
  registry:
    image: registry
    restart: always
    volumes:
      - './registry:/var/lib/registry'
    networks:
      - dev
    ports:
      - 5000:5000
networks:
  dev:
    driver: bridge