version: '3'
services:
  jetbrains_youtrack:
    name: youtrack-server-instance
    image: jetbrains/youtrack:2020.4.6808
    restart: always
    volumes:
      - './data:/opt/youtrack/data'
      - './conf:/opt/youtrack/conf'
      - './logs:/opt/youtrack/logs'
      - './backups:/opt/youtrack/backups'
    ports:
      - '8080:8080'
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
