version: '3'
services:
  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    restart: always
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap.chiqtv.cn
      - PHPLDAPADMIN_HTTPS=false
    networks:
      - dev
    ports:
      - 280:80
networks:
  dev:
    driver: bridge