version: "3"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    restart: always
    environment:
      - 'discovery.type=single-node'
    ports:
      - '5601:5601'
    networks:
      - dev
networks:
  dev:
    driver: bridge