version: '3'
services:
  jetbrains_teamcity:
    name: teamcity-server-instance
    image: jetbrains/teamcity-server
    restart: always
    volumes:
      - './data:/data/teamcity_server/datadir'
      - './logs:/opt/teamcity/logs'
    ports:
      - '8111:8111'
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
