version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '111.9.116.162'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.chiqtv.cn'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = '120011676@qq.com'
        gitlab_rails['gitlab_email_display_name'] = 'Gitlab Administrators'
        gitlab_rails['gitlab_email_reply_to'] = '120011676@qq.com'
        gitlab_rails['gitlab_email_subject_suffix'] = 'gitlab-'
        
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "120011676@qq.com"
        gitlab_rails['smtp_password'] = "hrllwxgfmtqkbhbh"
        gitlab_rails['smtp_domain'] = "qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
          main:
            label: 'LDAP'
            host: 'ldap.chiqtv.cn'
            port: 389
            uid: 'uid'
            bind_dn: 'cn=admin,dc=chiqtv,dc=cn'
            password: '1qaz2wsx'
            encryption: 'plain'
            active_directory: true
            allow_username_or_email_login: false
            block_auto_created_users: false
            base: 'ou=users,ou=hlj,dc=chiqtv,dc=cn'
            user_filter: ''
            attributes:
              username: ['uid', 'userid', 'sAMAccountName']
              email:    ['mail', 'email', 'userPrincipalName']
              name:       'cn'
              first_name: 'givenName'
              last_name:  'sn'
        EOS
    ports:
      - '180:80'
      - '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    networks:
      - "dev"
networks:
  dev:
    driver: bridge