version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    restart: always
    environment:
      - discovery.type=single-node
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - ELASTIC_PASSWORD==[;._PL<0okm
      - KIBANA_PASSWORD==[;._PL<0okm
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - dev
networks:
  dev:
    driver: bridge