version: '3'
services:
  projector-idea-c:
    image: registry.jetbrains.team/p/prj/containers/projector-idea-c
    restart: always
    ports:
      - 8887:8887
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
