version: '3'
services:
  nginx:
    image: nginx:1.13.6-alpine
    restart: always
    volumes:
      - './conf.d/:/etc/nginx/conf.d/:ro'
    networks:
      - dev
    ports:
      - 80:80
      - 443:443
networks:
  dev:
    driver: bridge