version: '3'
services:
  jetbrains_hub:
    name: hub-server-instance
    image: jetbrains/hub:2020.1.12669
    restart: always
    volumes:
      - './data:/opt/hub/data'
      - './conf:/opt/hub/conf'
      - './logs:/opt/hub/logs'
      - './backups:/opt/hub/backups'
    ports:
      - '8080:8080'
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
