version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    volumes:
      - './home:/var/jenkins_home'
    ports:
      - '8080:8080'
      - '50000:50000'
    networks:
      - "dev"
networks:
  dev:
    driver: bridge