version: "3"
services:
  portainer:
    image: portainer/portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "9000:9000"