version: "3"
services:
  portainer:
    image: portainer/portainer
#    restart: always
#    command: -H unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "./data:/data"
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
#  none、on-failure 以及any(默认) 
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    ports:
      - "9000:9000"
