version: '3'
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD==[;.-pl,0okm
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+8:00' --log-timestamps=SYSTEM --explicit_defaults_for_timestamp=1
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
