version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    volumes:
      - './data:/data'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: =[;._PL<0okm
    command: server
    networks:
      - dev
    ports:
      - 9000:9000
networks:
  dev:
    driver: bridge
