version: '3'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: =[;._PL<0okm
    volumes:
      - ./data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
