version: '3'
services:
  jmeter-server:
    image: openjdk:alpine
    restart: always
    volumes:
      - ./jmeter:/jmeter
    working_dir: /jmeter/bin
    command: ./jmeter-server
    expose:
      - 1099
    ports:
      - 1099:1099
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
