version: "3"
services:
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        restart: always
      placement:
        constraints: [node.role == manager]
    ports:
      - "9001:8080"
