version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo/db:/data/db
    ports:
      - 27017:27017
    networks:
      - "dev"
networks:
  dev:
    driver: bridge