version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    command:
      - redis-server --appendonly no --maxmemory-policy allkeys-lru --requirepass "=[;._PL<0okm"
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
