version: '3'
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
    networks:
      - "dev"
networks:
  dev:
    driver: bridge
